[package]
name = "picsort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
lazy_static = "*"
clap = { version = "4.0", features = ["derive"] }
tempfile = "*"
kamadak-exif = "0.5.5"
